site_name: Отчет по лабораторным работам

nav:
  - Главная: index.md
  - Лабораторная 1:
      - Оглавление: lab1/index_lab1.md 
      - Задание 1: lab1/task1.md
      - Задание 2: lab1/task2.md
      - Задание 3: lab1/task3.md
      - Задание 4: lab1/task4.md
      - Задание 5: lab1/task5.md
  - Лабораторная 2: lab2/index2.md
  - Лабораторная 3: lab3/index3.md
  - Лабораторная 4: lab4/index4.md
